### ISSUE TITLE
Camera compatibility with external mods

### ISSUE THREAD

**Issue by saki7** [SETNAHQ/Shicho#22]
- **Camera Positions Utility** [Workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=898480258) [GitHub](https://github.com/TPBCS/CameraPositions)
  - OK
- **TotalyFree Camera** [Workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=602077938) [GitHub](https://github.com/bloodypenguin/Skylines-TotalyFreeCamera)
  - OK
- **Cinematic Camera Extended** [Workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=785528371) [GitHub](https://github.com/SamsamTS/CS-CinematicCameraExtended)
  - Not working
- **Enhanced Zoom Continued** [Workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=651056665) [GitHub](https://github.com/vukivan/EnhancedZoomContinued)
  - Not working

## Important notice

Please never report compatibility issues to external mods. Also, this issue is just a memo, and does not mean that we are going to support anything in future.

**Comment by Mvek** [comment]
Hello, I have found out an incompatibility with Camera Positions Utility - its Disable building collision (and maybe some others too, but disable water collisions works fine) is not working when Shicho is On. And unfortunately Shicho does not allow such feature. Would it be possible to either implement that functionality or find a way to not override the functionality of Camera Positions Utility?

**Comment by saki7** [comment]
I really appreciate your report. However, it's an intended design choice for Shicho; the collision is meant to be disabled in camera view.

The rationale for this choice is because the game's 3D models are never meant to be crafted to exactly collide like the ones in third-person action games. The buildings in this game are basically just bunch of abstract boxes (i.e. low-poly models), so the vanilla game is just adding some arbitrary distance (i.e. the distance between camera & building) when the camera moves. So it's never been a 'collision' anyway.

**Comment by Mvek** [comment]
I see, but could it be possible as improvement in future to add checkbox to enable the collision? The reason is that it seems to me that with the enabled collision I can get a better angle for camera shots/screenshots than with it disabled, when it jumps me on the roof. But I guess that some first person camera mod could help here too if it is about camera angle from street level.
