### ISSUE TITLE
情報アイコンがオフのときにシネマティックカメラを使うと情報アイコンが表示されてしまう

### ISSUE THREAD

**Issue by tokachi269** [SETNAHQ/Shicho#29]
デフォのシネマチックカメラとCinematic camera extendで発生しました。
地区名も同様

**Comment by saki7** [comment]
これは調べたんですがCCE（やバニラのカメラ）がカメラモード変更を検知して自動で設定を変えてるようなのでShichoで対応するのは無理ぽですすいません
