### ISSUE TITLE
Mod is incompatible with a lot of mods

### ISSUE THREAD

**Issue by zarte13** [SETNAHQ/Shicho#33]
Here is the list:
https://docs.google.com/spreadsheets/d/1mVFkj_7ij4FLzKs2QJaONNmb9Z-SRqUeG6xFGqEX1ew/htmlview?usp=sharing#

**Comment by saki7** [comment]
This is not a valid issue, at all.

Please read the description written in your link. I am tired of unkind comments which were involved in this mod development. I will not fix any kind of bugs unless I'm getting some kind of rewards.
